name: 'Workflow: Learning'
run-name: 'Workflow Run: Learning'
on: workflow_dispatch
jobs:
  job-learning:
    name: 'Job: Learning'
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'list-things'
        name: 'Step: List Things'
        run: |
          env | sort
          ls -al ${XDG_RUNTIME_DIR}
          ls -al ${XDG_CONFIG_HOME}

