name: 'Action: Maven Verify'
run-name: 'Action Run: Maven Verify'
on:
  - 'push'
jobs:
  job-mvn-verify:
    name: 'Maven Verify'
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'checkout'
        name: 'Step: Checkout'
        uses: 'actions/checkout@v4'
      - id: 'setup-java'
        name: 'Step: Set Up Java and Maven'
        uses: 'actions/setup-java@v3'
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: '11'
      - id: 'mvn-verify'
        name: 'Step: Maven Verify'
        run: 'mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=info verify'
