name: 'Workflow: Maven Release: Prepare and Perform'
run-name: 'Workflow Run: Maven Release: Prepare and Perform'
on:
  - 'workflow_dispatch'
jobs:
  job-mvn-release-prepare-perform:
    name: 'Job: Maven Release: Prepare and Perform'
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'checkout'
        name: 'Step: Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          token: '${{ secrets.PUSH_TOKEN }}'
      - id: 'setup-java'
        name: 'Step: Set Up Java and Maven'
        uses: 'actions/setup-java@v3'
        with:
          cache: 'maven'
          distribution: 'temurin'
          gpg-passphrase: 'GPG_PASSPHRASE'
          gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
          java-version: '11'
          mvn-toolchain-id: 'Temurin 11'
          mvn-toolchain-vendor: 'openjdk' # see ../../pom.xml
          server-id: 'sonatype-oss-repository-hosting' # see https://github.com/microbean/microbean-parent/blob/master/pom.xml#L38
          server-password: 'SONATYPE_OSSRH_PASSWORD'
          server-username: 'SONATYPE_OSSRH_USERNAME'
      - id: 'mvn-release-prepare-perform'
        name: 'Step: Maven Release: Prepare and Perform'
        env:
          GPG_PASSPHRASE: '${{ secrets.GPG_PASSPHRASE }}'
          SONATYPE_OSSRH_PASSWORD: '${{ secrets.SONATYPE_OSSRH_PASSWORD }}'
          SONATYPE_OSSRH_USERNAME: '${{ secrets.SONATYPE_OSSRH_USERNAME }}'
        run: |
          mvn --batch-mode release:prepare release:perform -DdryRun=true
