name: 'Workflow: Test Git And Secrets'
run-name: 'Workflow Run: Test Git And Secrets'
on:
  - 'workflow_dispatch'
jobs:
  job-test-git-and-secrets:
    name: 'Job: Test Git And Secrets'
    permissions: {}
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'checkout'
        name: 'Step: Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: 'test-git-and-secrets'
        name: 'Step: Test Git And Secrets'
        env:
          GIT_ASKPASS: '${{ github.workspace }}/.askpass'
          GITHUB_TOKEN: '${{ secrets.PUSH_TOKEN }}'
        run: |
          echo 'echo ${GITHUB_TOKEN}' > "${GITHUB_WORKSPACE}/.askpass"
          chmod +x "${GITHUB_WORKSPACE}/.askpass"
          env | sort
          echo "Testing" >> deleteme
          git config user.email "learning.github.actions@example.com"
          git config user.name "Learning Github Actions"
          git config -l | sort
          git add deleteme
          git commit -m "Added line to deleteme"
          git push origin
